from __future__ import annotations

import html
import logging
from datetime import datetime, timezone
from typing import Any

from fpdf import FPDF

_LOG = logging.getLogger("ainvestify.report")

FOOTER_LINE = "AInvestify · Experimental research summary — not financial advice"

CREATORS = [
    {
        "name": "Sriram Kancherla",
        "role": "Co-creator",
        "link": "https://www.linkedin.com/in/sriram-kancherla-80a7b028a/",
    },
    {
        "name": "Viswanath Parshuram Yadavalli",
        "role": "Co-creator",
        "link": "https://www.linkedin.com/in/vish-yadavalli-65503628b/",
    },
]

DISCLAIMER_FULL = (
    "AInvestify is an experimental, educational project — not a licensed research product. "
    "Its scores and “model view” phrases are produced by machine-learning models on public data "
    "and may be inaccurate, incomplete, or out of date. Nothing here is investment, tax, or legal "
    "advice, and it should not be used as the sole basis for any financial decision. Verify material "
    "facts independently and consult a licensed professional before investing."
)

NOTICE_SHORT = (
    "This report is generated by an experimental AI model. Figures and recommendations may be "
    "inaccurate — verify independently before making any decisions."
)


def _esc(value: Any) -> str:
    if value is None:
        return ""
    return html.escape(str(value).strip(), quote=True)


def _safe_pdf_text(value: Any) -> str:
    if value is None:
        return ""
    s = str(value).strip()
    if not s:
        return ""
    return (
        s.replace("\r\n", "\n")
        .replace("\u2019", "'")
        .replace("\u2018", "'")
        .replace("\u201c", '"')
        .replace("\u201d", '"')
        .replace("\u2022", "-")
        .replace("\u2013", "-")
        .replace("\u2014", "-")
        .encode("latin-1", "replace")
        .decode("latin-1")
    )


def _tone_from_recommendation(rec: str | None) -> str:
    """Left-bar tone for the model-view callout."""
    s = (rec or "").lower()
    if "bearish sentiment" in s:
        return "tone-bear"
    if "bullish sentiment" in s:
        return "tone-bull"
    if "neutral sentiment" in s:
        return "tone-neutral"
    if any(x in s for x in ("bear", "negative", "sell")):
        return "tone-bear"
    if any(x in s for x in ("bull", "positive", "buy")):
        return "tone-bull"
    return "tone-neutral"


def _sentiment_dot(sent: str | None) -> str:
    s = (sent or "").lower()
    if "bull" in s or "positive" in s:
        return "dot-bull"
    if "bear" in s or "negative" in s:
        return "dot-bear"
    return "dot-neutral"


def _stock_block(payload: dict, key: str) -> dict[str, Any] | None:
    s = payload.get(key)
    if isinstance(s, dict) and (s.get("ticker") or s.get("company_name")):
        return s
    return None


def _fundamentals_rows(stock: dict[str, Any]) -> list[tuple[str, str]]:
    fund = stock.get("fundamentals")
    if not isinstance(fund, dict) or not fund:
        return []
    return [(str(k), str(v)) for k, v in fund.items()]


def _kpi_triple(stock: dict[str, Any]) -> tuple[str, str, str]:
    fund = stock.get("fundamentals") if isinstance(stock.get("fundamentals"), dict) else {}
    final = str(fund.get("Final Score", "—")) if fund else "—"
    fscore = str(fund.get("Fundamentals Score", "—")) if fund else "—"
    sscore = str(fund.get("Sentiment Score", "—")) if fund else "—"
    return final, fscore, sscore


# ---------------------------------------------------------------------------
# WeasyPrint (primary) — light-theme HTML/CSS matching the app design system.
# ---------------------------------------------------------------------------

def build_report_html(payload: dict[str, Any]) -> str:
    """Print-oriented HTML document (WeasyPrint). All dynamic text is escaped."""
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    primary = _stock_block(payload, "selected")
    compare = _stock_block(payload, "compare")

    def kv_table(rows: list[tuple[str, str]]) -> str:
        cells = "".join(
            f'<tr><td class="k">{_esc(k)}</td><td class="v">{_esc(v)}</td></tr>' for k, v in rows
        )
        return f'<table class="kv">{cells}</table>'

    def stock_section(title: str, stock: dict[str, Any], first: bool) -> str:
        ticker = _esc(stock.get("ticker") or "—")
        company = _esc(stock.get("company_name") or "—")
        rec = stock.get("recommendation")
        rec_s = _esc(rec)
        tone = _tone_from_recommendation(str(rec) if rec else None)
        sent_label = _esc(stock.get("sentiment_label") or "—")
        sent_dot = _sentiment_dot(str(stock.get("sentiment_label")))
        final_v, fund_v, sent_v = _kpi_triple(stock)

        price = stock.get("current_price")
        chg = stock.get("change_percent")
        mcap = _esc(stock.get("market_cap"))
        vol = _esc(stock.get("volume"))
        hi = stock.get("high_52w")
        lo = stock.get("low_52w")
        rng = "—"
        if hi is not None or lo is not None:
            rng = f'{_esc(lo if lo is not None else "—")} – {_esc(hi if hi is not None else "—")}'

        rec_block = ""
        if rec:
            rec_block = (
                f'<div class="callout {tone}"><p class="callout-label">Model view</p>'
                f'<p class="callout-text">{rec_s}</p></div>'
            )

        activity = kv_table(
            [
                ("Current price", str(price) if price is not None else "—"),
                ("Change (window)", f"{chg} %" if chg is not None else "—"),
                ("Market cap", mcap or "—"),
                ("Volume (last bar)", vol or "—"),
                ("52-week range", rng),
            ]
        )

        fund_rows = _fundamentals_rows(stock)
        fund_html = ""
        if fund_rows:
            fund_html = f'<h3>Model &amp; valuation metrics</h3>{kv_table(fund_rows)}'

        news = stock.get("news")
        news_html = ""
        if isinstance(news, list) and news:
            parts = []
            for item in news[:8]:
                if not isinstance(item, dict):
                    continue
                headline = _esc(item.get("title") or "—")
                src = _esc(item.get("source") or "")
                nd = _sentiment_dot(str(item.get("sentiment")))
                parts.append(
                    f'<div class="hl"><span class="dot {nd}"></span>'
                    f'<span class="hl-text">{headline}</span>'
                    + (f'<span class="hl-src">{src}</span>' if src else "")
                    + "</div>"
                )
            more = ""
            extra = len(news) - 8
            if extra > 0:
                more = f'<p class="note">+{extra} more — see the full list in-app.</p>'
            news_html = "<h3>Recent headlines</h3>" + '<div class="hl-list">' + "".join(parts) + "</div>" + more

        # First (primary) section follows the cover on page 1 — no forced break.
        cls = "stock-block" if first else "stock-block page-break"
        return f"""
        <section class="{cls}">
          <div class="sec-head">
            <span class="company">{company}</span>
            <span class="tick">{ticker}</span>
          </div>
          <div class="kpi-row">
            <div class="kpi"><span class="kpi-label">Final score</span><span class="kpi-val">{_esc(final_v)}</span></div>
            <div class="kpi"><span class="kpi-label">Fundamentals</span><span class="kpi-val">{_esc(fund_v)}</span></div>
            <div class="kpi"><span class="kpi-label">Sentiment</span><span class="kpi-val">{_esc(sent_v)}</span>
              <span class="sent"><span class="dot {sent_dot}"></span>{sent_label}</span></div>
          </div>
          {rec_block}
          <h3>Price &amp; activity</h3>
          {activity}
          {fund_html}
          {news_html}
        </section>
        """

    if primary:
        stocks_html = stock_section("Primary holding", primary, first=True)
    else:
        stocks_html = '<section class="stock-block page-break"><p class="muted">No primary stock was included in this export.</p></section>'
    if compare:
        stocks_html += stock_section("Comparison holding", compare, first=False)

    port_html = ""
    portfolio = payload.get("portfolio")
    if isinstance(portfolio, dict) and portfolio:
        summary = portfolio.get("summary") if isinstance(portfolio.get("summary"), dict) else portfolio
        rows = [
            ("Total market value", str(summary.get("total_market_value", "—"))),
            ("Total cost basis", str(summary.get("total_cost_basis", "—"))),
            ("Total P/L", str(summary.get("total_pnl", "—"))),
            ("Total P/L %", str(summary.get("total_pnl_pct", "—"))),
        ]
        cells = "".join(f'<tr><td class="k">{_esc(k)}</td><td class="v">{_esc(v)}</td></tr>' for k, v in rows)
        port_html = f"""
        <section class="page-break">
          <h2>Portfolio summary</h2>
          <p class="note">Session snapshot — server memory only, not a persisted account statement.</p>
          <table class="kv">{cells}</table>
        </section>
        """

    events_html = ""
    events = payload.get("events")
    if isinstance(events, list) and events:
        ev_parts = []
        for ev in events[:20]:
            if not isinstance(ev, dict):
                continue
            etype = _esc(ev.get("event_type") or "Event")
            when = _esc(ev.get("event_date") or "—")
            details = _esc(ev.get("details") or "")
            ev_parts.append(
                f'<div class="ev-row"><span class="ev-date">{when}</span>'
                f'<span class="ev-type">{etype}</span>'
                + (f'<span class="ev-det">{details}</span>' if details else "")
                + "</div>"
            )
        events_html = f"""
        <section class="page-break">
          <h2>Event calendar</h2>
          <p class="note">Best-effort upcoming events from public data sources.</p>
          <div class="ev-list">{"".join(ev_parts)}</div>
        </section>
        """

    creator_rows = "".join(
        f'<div class="cr-row"><span class="cr-name">{_esc(c["name"])}</span>'
        f'<span class="cr-role">{_esc(c["role"])}</span>'
        f'<a class="cr-link" href="{_esc(c["link"])}">LinkedIn</a></div>'
        for c in CREATORS
    )
    closing = f"""
        <section class="page-break">
          <h2>Disclaimer &amp; creators</h2>
          <p class="disclaimer">{_esc(DISCLAIMER_FULL)}</p>
          <h3>Creators</h3>
          <div class="cr-list">{creator_rows}</div>
        </section>
    """

    css = """
    @page {
      size: A4; margin: 16mm;
      @bottom-center {
        content: "AInvestify · Experimental research summary — not financial advice · Page " counter(page) " of " counter(pages);
        font-size: 9pt; color: #A1A3AC;
      }
    }
    * { box-sizing: border-box; }
    body {
      font-family: "Helvetica Neue", Helvetica, "DejaVu Sans", Arial, sans-serif;
      font-size: 10pt; line-height: 1.5; color: #14151A; background: #fff; margin: 0;
    }
    /* Cover — compact masthead folded onto the top of page 1 (not its own page). */
    .cover { padding-bottom: 4px; margin-bottom: 18px; border-bottom: 1px solid #EAEAE8; }
    .cover-top { display: flex; align-items: flex-start; gap: 14px; }
    .mark {
      display: inline-block; width: 34px; height: 34px; border-radius: 8px;
      background: #2563EB; color: #fff; text-align: center; line-height: 34px;
      font-weight: 700; font-size: 13pt; flex: 0 0 auto;
    }
    .cover-id { flex: 1; }
    .cover h1 { margin: 0; font-size: 22pt; font-weight: 500; letter-spacing: -0.02em; color: #14151A; }
    .cover .tag { margin: 2px 0 0; font-size: 11pt; color: #6B6D76; }
    .cover .rule { width: 40mm; height: 2px; background: #2563EB; margin: 8px 0; }
    .cover .when { margin: 0; font-size: 8.5pt; color: #A1A3AC; font-family: "DejaVu Sans Mono", monospace; }
    .notice {
      margin-top: 12px; background: #FDF6EC; border: 1px solid #F0E2C6; border-radius: 8px;
      padding: 9px 12px; font-size: 8.5pt; color: #7A5B1E;
    }
    /* Section headings */
    h2 { font-size: 14pt; font-weight: 600; color: #14151A; margin: 0 0 10px; }
    h3 {
      font-size: 8.5pt; font-weight: 600; color: #6B6D76; margin: 18px 0 8px;
      text-transform: uppercase; letter-spacing: 0.08em;
    }
    .sec-head { display: flex; align-items: center; gap: 8px; padding-bottom: 8px; border-bottom: 1px solid #EAEAE8; margin-bottom: 12px; }
    .company { font-size: 16pt; font-weight: 500; color: #14151A; }
    .tick {
      font-family: "DejaVu Sans Mono", monospace; font-size: 9pt; color: #6B6D76;
      background: #F5F5F4; border: 1px solid #EAEAE8; border-radius: 6px; padding: 2px 8px;
    }
    /* KPI cards — flat, hairline, no shadow */
    .kpi-row { display: flex; gap: 10px; margin-bottom: 14px; }
    .kpi { flex: 1; border: 1px solid #EAEAE8; border-radius: 10px; padding: 12px; background: #fff; }
    .kpi-label { display: block; font-size: 8pt; text-transform: uppercase; letter-spacing: 0.08em; color: #A1A3AC; }
    .kpi-val { display: block; font-size: 15pt; font-weight: 600; color: #14151A; margin-top: 4px; font-family: "DejaVu Sans Mono", monospace; }
    .sent { display: inline-flex; align-items: center; gap: 5px; margin-top: 6px; font-size: 8.5pt; color: #6B6D76; }
    .dot { display: inline-block; width: 8px; height: 8px; border-radius: 999px; background: #A1A3AC; }
    .dot-bull { background: #0F9D58; }
    .dot-bear { background: #D93025; }
    .dot-neutral { background: #A1A3AC; }
    /* Model-view callout — white with a colored left bar only */
    .callout { border: 1px solid #EAEAE8; border-left: 3px solid #A1A3AC; border-radius: 8px; padding: 10px 14px; margin: 12px 0; }
    .callout.tone-bull { border-left-color: #0F9D58; }
    .callout.tone-bear { border-left-color: #D93025; }
    .callout.tone-neutral { border-left-color: #A1A3AC; }
    .callout-label { margin: 0; font-size: 8pt; text-transform: uppercase; letter-spacing: 0.08em; color: #A1A3AC; }
    .callout-text { margin: 4px 0 0; font-size: 10pt; color: #14151A; }
    /* Key/value lists — shared between Price & Activity and Metrics */
    table.kv { width: 100%; border-collapse: collapse; }
    table.kv td { padding: 7px 0; border-bottom: 1px solid #EAEAE8; font-size: 9.5pt; vertical-align: top; }
    table.kv td.k { color: #6B6D76; }
    table.kv td.v { text-align: right; font-family: "DejaVu Sans Mono", monospace; font-weight: 600; color: #14151A; }
    /* Headlines — single-line rows, hairline dividers */
    .hl-list { margin-top: 4px; }
    .hl { display: flex; align-items: center; gap: 8px; padding: 7px 0; border-bottom: 1px solid #EAEAE8; font-size: 9.5pt; }
    .hl-text { flex: 1; color: #14151A; }
    .hl-src { color: #A1A3AC; font-size: 8pt; }
    /* Events — compact rows */
    .ev-row { display: flex; gap: 10px; padding: 7px 0; border-bottom: 1px solid #EAEAE8; font-size: 9.5pt; }
    .ev-date { font-family: "DejaVu Sans Mono", monospace; color: #6B6D76; width: 26mm; }
    .ev-type { font-weight: 600; color: #14151A; width: 40mm; }
    .ev-det { flex: 1; color: #6B6D76; }
    /* Creators */
    .cr-row { display: flex; align-items: center; gap: 10px; padding: 9px 0; border-bottom: 1px solid #EAEAE8; }
    .cr-name { font-weight: 600; color: #14151A; font-size: 10pt; flex: 1; }
    .cr-role { color: #6B6D76; font-size: 9pt; }
    .cr-link { color: #2563EB; font-size: 9pt; text-decoration: none; }
    .disclaimer { font-size: 9.5pt; color: #14151A; line-height: 1.6; }
    .note { font-size: 8.5pt; color: #A1A3AC; margin: 0 0 10px; }
    .muted { color: #6B6D76; }
    .page-break { break-before: page; }
    """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>AInvestify Report</title>
  <style>{css}</style>
</head>
<body>
  <section class="cover">
    <div class="cover-top">
      <span class="mark">AI</span>
      <div class="cover-id">
        <h1>AInvestify</h1>
        <p class="tag">Equity insight report</p>
        <div class="rule"></div>
        <p class="when">Generated {_esc(generated)}</p>
      </div>
    </div>
    <div class="notice">{_esc(NOTICE_SHORT)}</div>
  </section>
  {stocks_html}
  {port_html}
  {events_html}
  {closing}
</body>
</html>
"""


# ---------------------------------------------------------------------------
# fpdf2 fallback — same content/order, plain-text light layout.
# ---------------------------------------------------------------------------

_INK = (20, 21, 26)
_MUTED = (107, 109, 118)
_FAINT = (161, 163, 172)
_BLUE = (37, 99, 235)
_BORDER = (234, 234, 232)


class _ReportPDF(FPDF):
    def footer(self) -> None:
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*_FAINT)
        self.cell(0, 8, _safe_pdf_text(f"{FOOTER_LINE} · Page {self.page_no()} of {{nb}}"), align="C")
        self.set_text_color(*_INK)


def _rule(pdf: FPDF, width: float = 40.0) -> None:
    pdf.set_draw_color(*_BLUE)
    pdf.set_line_width(0.5)
    y = pdf.get_y()
    pdf.line(pdf.l_margin, y, pdf.l_margin + width, y)
    pdf.set_draw_color(*_BORDER)
    pdf.set_line_width(0.2)
    pdf.ln(4)


def _write_stock_sections(pdf: FPDF, title: str, stock: dict[str, Any]) -> None:
    ticker = stock.get("ticker") or "—"
    company = stock.get("company_name") or "—"
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_INK)
    pdf.multi_cell(0, 8, _safe_pdf_text(f"{company}  [{ticker}]"))
    pdf.set_draw_color(*_BORDER)
    pdf.set_line_width(0.2)
    y = pdf.get_y() + 1
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(4)

    final_v, fund_v, sent_v = _kpi_triple(stock)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(
        0, 5,
        _safe_pdf_text(f"Final score: {final_v}    Fundamentals: {fund_v}    Sentiment: {sent_v} ({stock.get('sentiment_label') or '—'})"),
    )

    rec = stock.get("recommendation")
    if rec:
        pdf.ln(1)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_MUTED)
        pdf.set_x(pdf.l_margin)
        pdf.cell(0, 5, "MODEL VIEW", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*_INK)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 5, _safe_pdf_text(str(rec)))

    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*_MUTED)
    pdf.set_x(pdf.l_margin)
    pdf.cell(0, 5, "PRICE & ACTIVITY", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_INK)
    hi, lo = stock.get("high_52w"), stock.get("low_52w")
    rng = f"{lo if lo is not None else '—'} - {hi if hi is not None else '—'}"
    lines = [
        f"Current price: {stock.get('current_price') if stock.get('current_price') is not None else '—'}",
        f"Change (window): {stock.get('change_percent') if stock.get('change_percent') is not None else '—'} %",
        f"Market cap: {stock.get('market_cap') or '—'}",
        f"Volume (last bar): {stock.get('volume') or '—'}",
        f"52-week range: {rng}",
    ]
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 5, _safe_pdf_text("\n".join(lines)))

    fund = stock.get("fundamentals")
    if isinstance(fund, dict) and fund:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_MUTED)
        pdf.set_x(pdf.l_margin)
        pdf.cell(0, 5, "MODEL & VALUATION METRICS", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_INK)
        for k, v in fund.items():
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 4, _safe_pdf_text(f"- {k}: {v}"))

    news = stock.get("news")
    if isinstance(news, list) and news:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_MUTED)
        pdf.set_x(pdf.l_margin)
        pdf.cell(0, 5, "RECENT HEADLINES", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_INK)
        for item in news[:8]:
            if not isinstance(item, dict):
                continue
            headline = item.get("title") or "—"
            sent = item.get("sentiment") or "—"
            src = item.get("source") or ""
            block = f"- [{sent}] {headline}"
            if src:
                block += f" ({src})"
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 4, _safe_pdf_text(block))
        extra = len(news) - 8
        if extra > 0:
            pdf.set_text_color(*_FAINT)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 4, _safe_pdf_text(f"+{extra} more - see the full list in-app."))
            pdf.set_text_color(*_INK)


def _write_portfolio(pdf: FPDF, summary: dict[str, Any] | None) -> None:
    if not isinstance(summary, dict):
        return
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_INK)
    pdf.cell(0, 8, "Portfolio summary", ln=True)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*_FAINT)
    pdf.multi_cell(0, 4, _safe_pdf_text("Session snapshot - server memory only, not a persisted account statement."))
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_INK)
    lines = [
        f"Total market value: {summary.get('total_market_value', '—')}",
        f"Total cost basis: {summary.get('total_cost_basis', '—')}",
        f"Total P/L: {summary.get('total_pnl', '—')}",
        f"Total P/L %: {summary.get('total_pnl_pct', '—')}",
    ]
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 5, _safe_pdf_text("\n".join(lines)))


def _write_events(pdf: FPDF, events: Any) -> None:
    if not isinstance(events, list) or not events:
        return
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_INK)
    pdf.cell(0, 8, "Event calendar", ln=True)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*_FAINT)
    pdf.multi_cell(0, 4, _safe_pdf_text("Best-effort upcoming events from public data sources."))
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*_INK)
    for ev in events[:20]:
        if not isinstance(ev, dict):
            continue
        when = ev.get("event_date") or "—"
        etype = ev.get("event_type") or "Event"
        details = ev.get("details") or ""
        block = f"- {when}   {etype}"
        if details:
            block += f"\n  {details}"
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 4, _safe_pdf_text(block))
        pdf.ln(1)


def _build_report_pdf_fpdf(payload: dict[str, Any]) -> bytes:
    pdf = _ReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(16, 16, 16)
    pdf.add_page()

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Calm light masthead — folded onto the top of page 1 (no dedicated cover page).
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*_INK)
    pdf.set_x(pdf.l_margin)
    pdf.cell(0, 9, "AInvestify", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*_MUTED)
    pdf.set_x(pdf.l_margin)
    pdf.cell(0, 6, "Equity insight report", ln=True)
    pdf.ln(1)
    _rule(pdf, width=40)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*_FAINT)
    pdf.set_x(pdf.l_margin)
    pdf.cell(0, 5, _safe_pdf_text(f"Generated {generated}"), ln=True)

    # Amber notice box.
    pdf.ln(3)
    pdf.set_fill_color(253, 246, 236)
    pdf.set_draw_color(240, 226, 198)
    pdf.set_text_color(122, 91, 30)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 5, _safe_pdf_text(NOTICE_SHORT), border=1, fill=True)
    pdf.set_text_color(*_INK)
    pdf.set_draw_color(*_BORDER)

    # Hairline separator under the masthead, then the primary holding on the same page.
    pdf.ln(4)
    y = pdf.get_y()
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(4)

    primary = _stock_block(payload, "selected")
    if primary:
        _write_stock_sections(pdf, "Primary holding", primary)
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 5, _safe_pdf_text("No primary stock was included in this export."))

    compare = _stock_block(payload, "compare")
    if compare:
        pdf.add_page()
        _write_stock_sections(pdf, "Comparison holding", compare)

    portfolio = payload.get("portfolio")
    if isinstance(portfolio, dict) and portfolio:
        pdf.add_page()
        summ = portfolio.get("summary") if isinstance(portfolio.get("summary"), dict) else portfolio
        _write_portfolio(pdf, summ if isinstance(summ, dict) else None)

    events = payload.get("events")
    if isinstance(events, list) and events:
        pdf.add_page()
        _write_events(pdf, events)

    # Closing — full disclaimer + creators.
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_INK)
    pdf.cell(0, 8, "Disclaimer & creators", ln=True)
    pdf.ln(1)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 5, _safe_pdf_text(DISCLAIMER_FULL))
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*_MUTED)
    pdf.set_x(pdf.l_margin)
    pdf.cell(0, 5, "CREATORS", ln=True)
    for c in CREATORS:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*_INK)
        pdf.set_x(pdf.l_margin)
        pdf.cell(0, 5, _safe_pdf_text(f"{c['name']} — {c['role']}"), ln=True)
        pdf.set_font("Helvetica", "U", 9)
        pdf.set_text_color(*_BLUE)
        pdf.set_x(pdf.l_margin)
        pdf.cell(0, 5, "LinkedIn", ln=True, link=c["link"])
        pdf.set_text_color(*_INK)
        pdf.ln(1)

    return bytes(pdf.output(dest="S"))


def build_report_pdf_bytes(payload: dict[str, Any]) -> bytes:
    """Build a styled PDF via HTML+WeasyPrint when available; otherwise fpdf2."""
    try:
        from weasyprint import HTML
    except (ImportError, OSError) as e:
        _LOG.warning("weasyprint unavailable (%s); using fpdf2 fallback for reports", e)
        return _build_report_pdf_fpdf(payload)

    html_doc = build_report_html(payload)
    try:
        return HTML(string=html_doc, base_url=".").write_pdf()
    except Exception as e:
        _LOG.warning("weasyprint render failed (%s); using fpdf2 fallback", e)
        return _build_report_pdf_fpdf(payload)


def report_attachment_filename(payload: dict[str, Any]) -> str:
    """Download filename: AInvestify-<TICKER>-report.pdf (ASCII-safe)."""
    sel = payload.get("selected")
    t = ""
    if isinstance(sel, dict) and sel.get("ticker"):
        t = str(sel.get("ticker")).strip().upper()
    safe = "".join(c for c in t if c.isalnum() or c in "._-") or "Report"
    return f"AInvestify-{safe}-report.pdf"
